### Load The Data

In [1]:
path = r"C:\Users\vamsh\Downloads\archive (2)\netflix_titles.csv"

In [2]:
import pandas as pd  #import the pandas

In [3]:
df = pd.read_csv(path) # using pandas read the file

In [4]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

### Identify and handle missing values using .isnull()

In [5]:
df.isnull().sum()   #identifying the missing values

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [6]:
#df.fillna(0,inplace = True)  #Replacing with 0

In [7]:
df.dropna(inplace = True)  #drop rows with missing values

In [8]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [9]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
27,s28,Movie,Grown Ups,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",United States,"September 20, 2021",2010,PG-13,103 min,Comedies,Mourning the loss of their beloved junior high...
28,s29,Movie,Dark Skies,Scott Stewart,"Keri Russell, Josh Hamilton, J.K. Simmons, Dak...",United States,"September 19, 2021",2013,PG-13,97 min,"Horror Movies, Sci-Fi & Fantasy",A family’s idyllic suburban life shatters when...
29,s30,Movie,Paranoia,Robert Luketic,"Liam Hemsworth, Gary Oldman, Amber Heard, Harr...","United States, India, France","September 19, 2021",2013,PG-13,106 min,Thrillers,"Blackmailed by his company's CEO, a low-level ..."
38,s39,Movie,Birth of the Dragon,George Nolfi,"Billy Magnussen, Ron Yuan, Qu Jingjing, Terry ...","China, Canada, United States","September 16, 2021",2017,PG-13,96 min,"Action & Adventure, Dramas",A young Bruce Lee angers kung fu traditionalis...
41,s42,Movie,Jaws,Steven Spielberg,"Roy Scheider, Robert Shaw, Richard Dreyfuss, L...",United States,"September 16, 2021",1975,PG,124 min,"Action & Adventure, Classic Movies, Dramas",When an insatiable great white shark terrorize...

### Remove duplicate rows using .drop_duplicates()

In [10]:
#check the duplicates

duplicate = df[df.duplicated()]

In [11]:
print(duplicate)  #duplicates not found, incase if it is available use syntax "df.drop_dupplicates"

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

### Standardize text values like gender, country names, etc.

In [12]:
df['country'] = df['country'].str.strip().str.title()

In [13]:
print(df['country'].unique())

['United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia'
 'United Kingdom' 'United States' 'Germany, Czech Republic' 'India'
 'United States, India, France' 'China, Canada, United States'
 'South Africa, United States, Japan' 'Japan' 'Nigeria'
 'Spain, United States' 'United Kingdom, United States'
 'United Kingdom, Australia, France'
 'United Kingdom, Australia, France, United States'
 'United States, Canada' 'Germany, United States'
 'South Africa, United States' 'United States, Mexico'
 'United States, Italy, France, Japan'
 'United States, Italy, Romania, United Kingdom'
 'Australia, United States' 'Argentina, Venezuela'
 'United States, United Kingdom, Canada' 'China, Hong Kong' 'Canada'
 'Hong Kong' 'United States, China, Hong Kong' 'Italy, United States'
 'United States, Germany' 'France' 'United Kingdom, Canada, United States'
 'United States, United Kingdom' 'India, Nepal'
 'New Zealand, Australia, France, United States' 'Italy, Brazil, Greece'
 'Spain' 'Colombia' 'United States, Japan' 'Mexico'
 'Switzerland, United Kingdom, Australia' 'South Africa'
 'Canada, United States' 'Argentina' 'Argentina, Spain'
 'United States, Nigeria' 'Taiwan' 'Bulgaria, United States'
 'Spain, United Kingdom, United States' 'United States, China'
 'United States, France' 'Spain, France, United Kingdom, United States'
 ', France, Algeria' 'Poland'
 'France, Israel, Germany, United States, United Kingdom' 'Australia'
 'New Zealand' 'Saudi Arabia' 'Thailand' 'Indonesia' 'Italy'
 'United States, Switzerland' 'Hong Kong, Canada, United States'
 'Kuwait, United States' 'France, Canada, United States, Spain'
 'France, Netherlands, Singapore' 'Egypt' 'Malaysia'
 'South Korea, Czech Republic' 'South Korea' 'Vietnam'
 'United Kingdom, Belgium' 'United Kingdom, Australia, United States'
 'France, Japan, United States'
 'United Kingdom, Germany, Spain, United States'
 'United Kingdom, United States, France, Italy'
 'United States, Germany, Canada'
 'United States, France, Italy, United Kingdom'
 'United States, United Kingdom, Germany, Hungary'
 'United States, New Zealand' 'Lebanon' 'Brazil' 'Romania'
 'Lebanon, Syria' 'Philippines' 'Germany' 'United States, India'
 'Philippines, Singapore, Indonesia' 'China, United States, Canada'
 'Lebanon, United Arab Emirates' 'Canada, United States, Denmark'
 'United Arab Emirates' 'Mexico, France, Colombia' 'Sweden'
 'Germany, United States, France' 'United States, Bulgaria'
 'United Kingdom, France, Germany, United States'
 'Syria, France, Lebanon, Qatar' 'Belgium, Netherlands' 'Mauritius'
 'Canada, South Africa' 'Austria' 'Mexico, Brazil' 'France, United States'
 'China' 'Turkey' 'Germany, France'
 'United Kingdom, France, Spain, United States' 'United States, Australia'
 'United States, United Kingdom, France' 'United States, Russia'
 'United States, United Kingdom, New Zealand'
 'Canada, Nigeria, United States'
 'France, United States, United Kingdom, Canada' 'India, United Kingdom'
 'Canada, United States, Mexico' 'United Kingdom, Germany, United States'
 'Czech Republic, United Kingdom, United States' 'China, Taiwan'
 'Cameroon' 'Netherlands' 'Japan, United States' 'Egypt, Saudi Arabia'
 'United Kingdom, France, Poland, Germany, United States'
 'Ireland, Switzerland, United Kingdom, France, United States'
 'China, United Kingdom' 'United Kingdom, South Africa, France'
 'Ireland, United Kingdom, France, Germany' 'Russia, United States'
 'United Kingdom, United States, France' 'United Kingdom,'
 'United States, India, United Kingdom' 'Kenya' 'Spain, Argentina'
 'India, United Kingdom, France, Qatar' 'Belgium, France'
 'Argentina, Chile' 'United States, Thailand' 'Chile, Brazil'
 'Canada, United States, United Kingdom'
 'United States, Cambodia, Romania' 'Bangladesh'
 'Spain, Belgium, United States'
 'United Kingdom, United States, Australia' 'Portugal, United States'
 'Portugal, Spain' 'India, United States' 'United Kingdom, Ireland'
 'United Kingdom, Spain, United States' 'Hungary, United States'
 'United States, South Korea' 'Canada, United States, Cayman Islands'
 'India, France' 'France, Canada' 'Canada, Hungary, United States'
 'Norway' 'Canada, United Kingdom, United States'
 'United Kingdom, Germany, France, United States' 'France, Algeria'
 'Philippines, Canada, United Kingdom, United States'
 'Ireland, France, Iceland, United States, Mexico, Belgium, United Kingdom, Hong Kong'
 'Singapore' 'France, Belgium' 'Iceland' 'United States, France, Serbia'
 'United States, Italy' 'Hong Kong, United States'
 'United States, Malta, France, United Kingdom'
 'United States, China, Canada' 'Spain, France, Canada'
 'United States, China, Colombia' 'Spain, Thailand, United States'
 'Mexico, Spain' 'Ireland, Luxembourg, Belgium' 'China, United States'
 'Canada, Belgium' 'Canada, United Kingdom'
 'Lebanon, United Arab Emirates, France, Switzerland, Germany'
 'France, Belgium, Italy' 'Lebanon, United States, United Arab Emirates'
 'Lebanon, France' 'France, Lebanon' 'France, Lebanon, United Kingdom'
 'France, Norway, Lebanon, Belgium' 'Lebanon, Canada, France'
 'Sweden, Czech Republic, United Kingdom, Denmark, Netherlands'
 'United States, United Kingdom, India' 'Indonesia, Netherlands'
 'Turkey, South Korea' 'Russia' 'Serbia, United States' 'Namibia'
 'United Kingdom, Kenya'
 'United Kingdom, France, United States, Belgium, Luxembourg, China, Germany'
 'United States, France, Canada, Belgium' 'Germany, China, United Kingdom'
 'Hong Kong, Iceland, United States'
 'United States, Belgium, Canada, France' 'South Africa, Angola'
 'United States, Philippines'
 'United States, United Kingdom, Canada, China'
 'United States, Canada, United Kingdom' 'Uruguay' 'Turkey, United States'
 'Peru, Germany, Norway' 'Mozambique' 'Brazil, France'
 'China, Spain, South Korea, United States' 'Spain, Germany'
 'Hong Kong, China' 'France, Belgium, Luxembourg, Cambodia,' 'Belgium'
 'Indonesia, United Kingdom' 'Switzerland, France, Belgium, United States'
 'Ghana' 'United Kingdom, Nigeria' 'Chile' 'France, Egypt' 'Egypt, France'
 'France, Brazil, Spain, Belgium' 'Egypt, Algeria'
 'Canada, South Korea, United States' 'Nigeria, United Kingdom'
 'United Arab Emirates, Jordan, Lebanon, Saudi Arabia'
 'Saudi Arabia, United Arab Emirates' 'Zimbabwe'
 'United Kingdom, Germany, United Arab Emirates, New Zealand'
 'Romania, United States' 'Mexico, United States' 'Kuwait'
 'Canada, Nigeria'
 'Saudi Arabia, Netherlands, Germany, Jordan, United Arab Emirates, United States'
 'United Kingdom, Germany, United States, France'
 'India, United Kingdom, China, Canada, Japan, South Korea, United States'
 'Turkey, India' 'Italy, Turkey' 'United Kingdom, United States, Japan'
 'France, Belgium, United States' 'Uruguay, Argentina'
 'United States, United Kingdom, Japan' 'United Kingdom, Italy'
 'Ireland, United Kingdom'
 'United Kingdom, France, Belgium, Canada, United States'
 'Netherlands, Germany, Denmark, United Kingdom' 'Hungary'
 'South Korea, United States' 'Romania, France, Switzerland, Germany'
 'France, Malta, United States'
 'United Kingdom, France, Belgium, Ireland, United States'
 'United States, Norway, Canada' 'Poland, United States'
 'Kenya, United States' 'France, South Korea, Japan, United States'
 'Taiwan, Malaysia' 'Uruguay, Argentina, Germany, Spain'
 'United States, United Kingdom, France, Germany, Japan'
 'United States, France, Japan' 'United Kingdom, France, United States'
 'Spain, France, United States' 'Indonesia, South Korea, Singapore'
 'United States, Spain' 'Argentina, Uruguay, Serbia'
 'Israel, United States' 'France, Japan'
 'United Kingdom, United States, Germany, Denmark, Belgium, Japan'
 'India, Germany' 'India, United Kingdom, Canada, United States'
 'Philippines, United States' 'Romania, Bulgaria, Hungary'
 'Uruguay, Guatemala' 'France, Senegal, Belgium' 'Canada, Norway'
 'United Kingdom, France' 'United States, Chile'
 'United Kingdom, Japan, United States' 'Spain, United Kingdom'
 'United States, South Korea, Japan' 'United Kingdom, Hungary, Australia'
 'Italy, Belgium' 'Switzerland' 'Singapore, Malaysia'
 'France, Belgium, Luxembourg, Romania, Canada, United States'
 'South Africa, Nigeria' 'Spain, France' 'Pakistan'
 'Denmark, Brazil, France, Portugal, Sweden' 'India, Turkey'
 'Philippines, Singapore' 'Taiwan, China, France, United States'
 'Colombia, Peru, United Kingdom' 'Thailand, China, United States'
 'Argentina, United States' 'Uruguay, Spain, Mexico'
 'France, Luxembourg, Canada' 'Chile, Argentina' 'Denmark' 'Italy, France'
 'Canada, Germany' 'Pakistan, United Arab Emirates' 'Ghana, United States'
 'Mexico, Finland' 'United Arab Emirates, United Kingdom, India'
 'Netherlands, Belgium' 'United States, Taiwan' 'United Kingdom, Malawi'
 'Paraguay, Argentina' 'United Kingdom, Russia, United States'
 'India, Pakistan' 'Indonesia, Singapore' 'Spain, Belgium'
 'Iceland, Sweden, Belgium' 'Uruguay, Argentina, Spain'
 'United Kingdom, Ireland, United States'
 'Canada, Germany, France, United States' 'United Kingdom, Japan'
 'Norway, Denmark, Netherlands, Sweden' 'Hong Kong, China, United States'
 'Ireland, Canada' 'Italy, Switzerland, France, Germany'
 'Mexico, Netherlands' 'France, Iran, United States'
 'United Kingdom, India' 'Russia, Poland, Serbia' 'Spain, Portugal' 'Peru'
 'Mexico, Argentina'
 'United Kingdom, Canada, United States, Cayman Islands'
 'Indonesia, United States'
 'United States, Israel, United Kingdom, Canada'
 'Norway, Iceland, United States' 'United Kingdom, India, United States'
 'India, Australia' 'Belgium, United Kingdom, United States'
 'India, Germany, Austria' 'Spain, Mexico' 'China, Japan'
 'Argentina, France' 'China, United States, United Kingdom'
 'France, Luxembourg, United States' 'China, United States, Australia'
 'Colombia, Mexico' 'United States, Canada, Ireland' 'Israel'
 'Chile, Peru' 'Canada, Japan, United States'
 'United Kingdom, Canada, United States, Germany'
 'Italy, Switzerland, Albania, Poland' 'Cambodia'
 'United States, Canada, Indonesia, United Kingdom, China, Singapore'
 'Spain, Colombia' 'Bulgaria'
 'Argentina, Brazil, France, Poland, Germany, Denmark'
 'United Kingdom, Spain, United States, Germany' 'Philippines, Qatar'
 'Netherlands, Belgium, Germany, Jordan'
 'United Arab Emirates, United States' 'United Kingdom, Germany'
 'United Kingdom, Canada' 'Soviet Union, India'
 'Australia, United Arab Emirates' 'Czech Republic, United States'
 'South Korea, China, United States' 'India, Soviet Union' 'India, Mexico'
 'Georgia, Germany, France' 'United Arab Emirates, Romania'
 'Australia, Canada' 'India, Malaysia' 'Germany, Jordan, Netherlands'
 'Turkey, France, Germany, Poland' 'Norway, Germany' 'France, Morocco'
 'Cambodia, United States'
 'United Kingdom, Italy, Israel, Peru, United States'
 'Argentina, Uruguay, Spain, France'
 'United Kingdom, France, United States, Belgium'
 'France, Canada, China, Cambodia'
 'United Kingdom, France, Belgium, United States' 'Ireland'
 'Chile, France' 'France, United Kingdom, India'
 'Czech Republic, Slovakia' 'Singapore, France' 'Spain, Switzerland'
 'South Africa, United States, Germany' 'Spain, Italy, Argentina'
 'Chile, Spain, Argentina, Germany' 'Austria, Czech Republic'
 'Lebanon, Qatar' 'United Kingdom, Jordan, Qatar, Iran'
 'France, South Korea, Japan' 'Israel, Germany, France'
 'United States, Hungary' 'France, Qatar'
 'United Kingdom, Germany, Canada' 'Ireland, South Africa'
 'Chile, United States, France' 'Belgium, France, Netherlands'
 'United States, Bermuda, Ecuador' 'United Kingdom, Egypt, United States'
 'United States, France, United Kingdom' 'Spain, Mexico, France'
 'United States, South Africa' 'Hong Kong, China, Singapore'
 'South Africa, China, United States' 'Denmark, France, Poland'
 'New Zealand, United Kingdom' 'Netherlands, Denmark, South Africa'
 'Iran, France' 'United Kingdom, United States, France, Germany'
 'Australia, France' 'Ireland, United Kingdom, United States'
 'Spain, Italy' 'United Kingdom, France, Germany' 'Canada, Luxembourg'
 'Brazil, Netherlands, United States, Colombia, Austria, Germany'
 'France, Canada, Belgium' 'Bulgaria, United States, Spain, Canada'
 'Sweden, Netherlands' 'France, United States, Mexico'
 'Australia, United Kingdom, United Arab Emirates, Canada'
 'Singapore, United States' 'India, Iran' 'France, Belgium, Spain'
 'Denmark, Sweden, Israel, United States' 'United States, Iceland'
 'United Kingdom, Russia' 'United States, Israel, Italy, South Africa'
 'South Korea, Japan' 'United Kingdom, Pakistan'
 'United Kingdom, Czech Republic, United States, Germany, Bahamas'
 'Germany, Sri Lanka' 'United States, Sweden'
 'United States, India, Bangladesh' 'United States, Canada, France'
 'Brazil, France, Germany' 'United States, United Kingdom, Australia'
 'Germany, United States, Hong Kong, Singapore'
 'France, Germany, Switzerland'
 'Germany, France, Luxembourg, United Kingdom, United States'
 'United Kingdom, Canada, Italy' 'Taiwan, Hong Kong, United States, China'
 'Germany, Australia' 'United Kingdom, Poland, United States'
 'United Kingdom, South Africa' 'Finland, Sweden, Norway, Latvia, Germany'
 'South Africa, United States, New Zealand, Canada'
 'United States, Italy, United Kingdom, Liechtenstein'
 'Denmark, France, Belgium, Italy, Netherlands, United States, United Kingdom'
 'United States, Australia, Mexico'
 'United Kingdom, Czech Republic, Germany, United States'
 'France, China, Japan, United States' 'Germany, Belgium'
 'Pakistan, Norway, United States'
 'United States, Canada, Belgium, United Kingdom' 'Venezuela'
 'Canada, Spain, France' 'United States, Indonesia' 'Spain, France, Italy'
 'United Arab Emirates, United States, United Kingdom'
 'United States, Brazil' 'United States, France, Mexico'
 'United States, Nicaragua' 'France, United Kingdom, United States'
 'United Kingdom, United States, Spain, Germany, Greece, Canada'
 'Italy, Canada, France' 'Thailand, United States'
 'United Kingdom, Denmark, Canada, Croatia'
 'United States, France, United Kingdom, Japan'
 'United States, United Kingdom, Denmark, Sweden'
 'United States, United Kingdom, Italy'
 'United States, France, Canada, Spain' 'Russia, United States, China'
 'United States, Canada, Germany' 'Ireland, United States'
 'United States, United Arab Emirates' 'United States, Ireland' 'Poland,'
 'Slovenia, Croatia, Germany, Czech Republic, Qatar'
 'United States, Spain, Germany' 'India, Japan'
 'United Kingdom, France, Belgium' 'Canada, Ireland, United States'
 'United Kingdom, United States, Dominican Republic'
 'Germany, United Kingdom, United States'
 'South Africa, Germany, Netherlands, France'
 'Ireland, United States, France' 'Germany, United States, Canada'
 'United Kingdom, Germany, Canada, United States'
 'United States, France, Canada, Lebanon, Qatar'
 'Netherlands, Belgium, United Kingdom, United States'
 'France, Belgium, China, United States' 'United States, Chile, Israel'
 'United Kingdom, Norway, Denmark, Germany, Sweden'
 'Norway, Denmark, Sweden' 'China, India, Nepal'
 'Colombia, Mexico, United States' 'United Kingdom, South Korea'
 'United States, Greece, Brazil' 'Germany, United Kingdom'
 'Argentina, Chile, Peru' 'Poland, West Germany' 'Canada, Spain'
 'United States, Cambodia' 'United States, Greece'
 'Norway, United Kingdom, France, Ireland' 'United Kingdom, Poland'
 'Pakistan, United States' 'Israel, Sweden, Germany, Netherlands'
 'Switzerland, France' 'Chile, Argentina, France, Spain, United States'
 'United States, India, South Korea, China'
 'Denmark, Germany, Belgium, United Kingdom, France'
 'Denmark, Germany, Belgium, United Kingdom, France, Sweden'
 'France, Switzerland, Spain, United States, United Arab Emirates'
 'Brazil, India, China, United States'
 'Denmark, France, United States, Sweden' 'Australia, Iraq'
 'China, Morocco, Hong Kong' 'Canada, United States, Germany'
 'United Kingdom, Thailand' 'France, Germany, Czech Republic, Belgium'
 'Switzerland, Vatican City, Italy, Germany, France'
 'Portugal, France, Poland, United States' 'India, Switzerland'
 'Canada, India' 'United States, Morocco' 'Singapore, Japan, France'
 'Canada, Mexico, Germany, South Africa'
 'United Kingdom, United States, Canada'
 'Germany, France, United States, Canada, United Kingdom' 'India, Canada'
 'Ireland, Canada, United Kingdom, United States'
 'United States, Germany, Australia' 'Australia, France, Ireland'
 'Australia, India' 'United States, United Kingdom, Canada, Japan'
 'Sweden, United Kingdom, Finland' 'Hong Kong, Taiwan'
 'United States, United Kingdom, Spain, South Korea' 'Guatemala'
 'United States, Germany, United Kingdom, Australia'
 'Italy, France, Switzerland' 'Canada, France, United States'
 'Switzerland, United States' 'Thailand, Canada, United States'
 'China, Hong Kong, United States' 'United Kingdom, New Zealand'
 'Czech Republic, United Kingdom, France'
 'Australia, United Kingdom, Canada' 'Jamaica, United States'
 'Australia, United Kingdom'
 'United Kingdom, France, Canada, Belgium, United States'
 'Denmark, United Kingdom, Sweden' 'United States, Hong Kong'
 'Argentina, France, United States, Germany, Qatar'
 'United States, Germany, United Kingdom'
 'United States, Germany, United Kingdom, Italy'
 'United States, New Zealand, United Kingdom' 'Finland, United States'
 'Spain, France, Uruguay' 'France, Canada, United States'
 'United States, Canada, China'
 'Ireland, Canada, Luxembourg, United States, United Kingdom, Philippines, India'
 'United States, Czech Republic, United Kingdom' 'Israel, Germany'
 'Mexico, France'
 'Israel, Germany, Poland, Luxembourg, Belgium, France, United States'
 'Austria, United States' 'United Kingdom, Lithuania'
 'United States, Greece, United Kingdom'
 'United Kingdom, China, United States, India'
 'United States, Sweden, Norway' 'United Kingdom, United States, Morocco'
 'United States, United Kingdom, Morocco' 'Spain, Canada, United States'
 'United States, India, United Arab Emirates'
 'United Kingdom, Canada, France, United States'
 'Belgium, Ireland, Netherlands, Germany, Afghanistan'
 'France, Canada, Italy, United States, China'
 'Ireland, United Kingdom, Greece, France, Netherlands'
 'New Zealand, United States'
 'United States, Australia, South Africa, United Kingdom'
 'United States, Germany, Mexico' 'United States, Czech Republic'
 'Somalia, Kenya, Sudan, South Africa, United States'
 'United States, Canada, Japan, Panama' 'United Kingdom, Spain, Belgium'
 'Serbia, South Korea, Slovenia'
 'Denmark, United Kingdom, South Africa, Sweden, Belgium'
 'Germany, Canada, United States' 'New Zealand, United Kingdom, Australia'
 'United Kingdom, Australia, Canada, United States'
 'United Kingdom, China, United States' 'United Kingdom, Brazil, Germany'
 'Canada, United States, India, United Kingdom'
 'Switzerland, United Kingdom, United States'
 'United States, United Kingdom, Germany' 'United Kingdom, India, Sweden'
 'United States, Argentina'
 'Germany, United States, United Kingdom, Canada'
 'United States, East Germany, West Germany'
 'Egypt, Austria, United States' 'Croatia, Slovenia, Serbia, Montenegro'
 'United Arab Emirates, Jordan']

In [14]:
df['rating'] = df['rating'].str.strip().str.title()

In [15]:
print(df['rating'].unique())

['Tv-Ma' 'Tv-14' 'Pg-13' 'Pg' 'R' 'Tv-Pg' 'G' 'Tv-Y7' 'Tv-G' 'Tv-Y'
 'Nc-17' 'Nr' 'Tv-Y7-Fv' 'Ur']

### Convert date formats to a consistent type (e.g., dd-mm-yyyy).

In [16]:
df["date_added"] = pd.to_datetime(df['date_added'],errors = "coerce")

In [17]:
df.head()["date_added"]

7    2021-09-24
8    2021-09-24
9    2021-09-24
12   2021-09-23
24   2021-09-21
Name: date_added, dtype: datetime64[ns]

### Rename column headers to be clean and uniform (e.g., lowercase, no spaces

In [18]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [19]:
df.columns = df.columns.str.strip().str.upper()
df.columns

Index(['SHOW_ID', 'TYPE', 'TITLE', 'DIRECTOR', 'CAST', 'COUNTRY', 'DATE_ADDED',
       'RELEASE_YEAR', 'RATING', 'DURATION', 'LISTED_IN', 'DESCRIPTION'],
      dtype='object')

In [20]:
df.head()

,SHOW_ID,TYPE,TITLE,DIRECTOR,CAST,COUNTRY,DATE_ADDED,RELEASE_YEAR,RATING,DURATION,LISTED_IN,DESCRIPTION
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,Tv-Ma,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,Tv-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,Pg-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021-09-23,2021,Tv-Ma,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,2021-09-21,1998,Tv-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

### Check and fix data types (e.g., age should be int, date as datetime

In [21]:
df.dtypes

SHOW_ID                 object
TYPE                    object
TITLE                   object
DIRECTOR                object
CAST                    object
COUNTRY                 object
DATE_ADDED      datetime64[ns]
RELEASE_YEAR             int64
RATING                  object
DURATION                object
LISTED_IN               object
DESCRIPTION             object
dtype: object

In [22]:
df["DURATION"] = df['DURATION'].str.extract('(\d+)').astype('float')

In [23]:
df.DURATION

7       125.0
8         9.0
9       104.0
12      127.0
24      166.0
        ...
8801     96.0
8802    158.0
8804     88.0
8805     88.0
8806    111.0
Name: DURATION, Length: 5332, dtype: float64

In [24]:
df.dtypes

SHOW_ID                 object
TYPE                    object
TITLE                   object
DIRECTOR                object
CAST                    object
COUNTRY                 object
DATE_ADDED      datetime64[ns]
RELEASE_YEAR             int64
RATING                  object
DURATION               float64
LISTED_IN               object
DESCRIPTION             object
dtype: object